### ISSUE TITLE
Imagens quebrando

### ISSUE THREAD

**Issue by reginaldojunior** [mtsalcova/livro-sem-apego#11]
![image](https://user-images.githubusercontent.com/7466894/28097562-3fed7e64-6687-11e7-87a5-1f1d7fe0f021.png)

As imagens na listagem de livros e na página do mesmo está quebrando quando não informada no cadastro, colocar uma imagem default informando ao usuário que não tem imagem cadastrada.

**Comment by mtsalcova** [comment]
Boa @reginaldojunior! Então, isso ocorreu pois houve um erro no upload, estou em contato com a pessoa que cadastrou esses livros para ver o que ocorreu, por hora vou setar a imagem default, caso venha vazio o src da imagem.

Valeu!

**Comment by mtsalcova** [comment]
Resolvido @reginaldojunior! ;)
